apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: batch-deployment
spec:
  selector:
    matchLabels:
      app: batch
  replicas: 1
  template:
    metadata:
      labels:
        app: batch
    spec:
      containers:
      - name: batch
        image: gcr.io/broad-ctsa/batch:be4db2baac746dc389e0cb5baa75bc214d831252b32f78c5bf6595e15dd36aab
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: batch
  labels:
    app: batch
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: batch
